spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clubs
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  sql:
    init:
      mode: always

  mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    type-aliases-package: com.example.clubs
    configuration:
      map-underscore-to-camel-case: true

jwt:

  secret-key: "U3VwZXJTZWNyZXRLZXlGb3JITUFDMjU2"
  refresh-secret-key: "UmVmcmVzaFNlY3JldEtleUZvckhTQTI1Ng=="
  access-token-expiration: 6000  #900000  # 15분 (밀리초)
  refresh-token-expiration: 604800000  # 7일 (밀리초)
